baseurl = "/"
languageCode = "en-us"
title = "plantarum.ca"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["~$", "\\#$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "#$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Notebooks"
    url = "/notebooks/"
    weight = 100
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 300
[[menu.main]]
    name = "Tutorials"
    url = "/tutorials/"
    weight = 200

[params]
    description = "Diversity and biogeography of crop wild relatives, weeds and invasive species"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "tybio-square.jpg"
    width = 50
    height = 50
    alt = "Tyler"


    [params.icon]
    url = "favicon.ico"
